version: "3.8"

services:
  dev:
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile
      args:
        workdir: ${DEVCONTAINER_WORKDIR}
    working_dir: ${DEVCONTAINER_WORKDIR}
    tty: true
    user: node
    volumes:
      - ./:${DEVCONTAINER_WORKDIR}
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4318:4318"
    environment:
      - LOG_LEVEL=debug
