version: "3.8"

services:

  dev:
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile
      args:
        workdir: /opt/dev
    working_dir: /opt/dev
    tty: true
    volumes:
      - ./:/opt/dev
