remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
defaults:
  - values:
      layout: 'default'
search_enabled: true
aux_links:
  "GitHub":
    - "https://github.com/kn0ll/tweb"