name: CI

on:
  push:
    branches:
      - master

jobs:
  Build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - run: npm install -g pnpm@9.7.1
      - run: pnpm install --frozen-lockfile
      - run: pnpm check
      - run: pnpm build
      - run: pnpm test
      - run: pnpm doc
      - uses: actions/configure-pages@v5
      - uses: actions/jekyll-build-pages@v1
        with:
          source: ./docs
      - uses: actions/upload-pages-artifact@v3
      - uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: packages/core/coverage
