name: Validate

on:
  push:
    branches:
      - master

jobs:
  build-dev:
    name: Build Dev Container
    runs-on: ubuntu-latest
    environment: testing

    steps:
      - uses: actions/checkout@v3
      - run: pnpm install --frozen-lockfile
      - run: pnpm lint
      - run: pnpm test
